LU Decomposition

In [1]:
import numpy as np
def ludec(A):
  n = A.shape[0]
  U = np.copy(A)
  L = np.identity(n)
  for j in range(n-1):
    for i in range(j+1,n):
      coeff = U[i,j]/U[j,j]
      U[i,j:] -= coeff*U[j,j:]
      L[i,j] = coeff
  return L, U
def lusolve(A,bs):
  L, U = ludec(A)
  ys = forsub(L,bs)
  xs = backsub(U,ys)
  return xs
def forsub(L,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in range(n):
    xs[i] = (bs[i] - L[i,:i]@xs[:i])/L[i,i]
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
def testcreate(n,val):
  A = np.arange(val,val+n*n).reshape(n,n)
  A = np.sqrt(A)
  bs = (A[0,:])**2.1
  return A, bs
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
A, bs = testcreate(4,21)
testsolve(lusolve,A,bs)

[ 17118.9554009  -55069.99934969  58822.07580723 -20866.39246612]
[ 17118.95550576 -55069.99968225  58822.07615809 -20866.39258928]


Gaussian elimnation doesn't work: \\
Example 1:
$(A|b)= \begin{bmatrix}  
  0 & -1 &| 1 \\
  1 & 1 &| 2 \end{bmatrix}$

In [2]:
import numpy as np
def gauelim(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs

def forsub(L,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in range(n):
    xs[i] = (bs[i] - L[i,:i]@xs[:i])/L[i,i]
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
Ap=[[0.,-1.], [1.,1.]]
bs=[1.,2.]
A = np.matrix(Ap)
print(A)
print(bs)
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
testsolve(gauelim,A,bs)

[[ 0. -1.]
 [ 1.  1.]]
[1.0, 2.0]
[nan nan]
[ 3. -1.]


<ipython-input-2-e1312c4eee02>:8: RuntimeWarning: divide by zero encountered in scalar divide
  coeff = A[i,j]/A[j,j]
<ipython-input-2-e1312c4eee02>:9: RuntimeWarning: invalid value encountered in multiply
  A[i,j:] -= coeff*A[j,j:]
<ipython-input-2-e1312c4eee02>:24: RuntimeWarning: invalid value encountered in scalar divide
  xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]


Example 2:
$(A|b)= \begin{bmatrix}  
  2 & 1 &1 & | 8 \\
  2 & 1 &-4  & |  -2 \\
  1 & 2 & 1  &| 2 \end{bmatrix}$

In [3]:
import numpy as np
def gauelim(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs

def forsub(L,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in range(n):
    xs[i] = (bs[i] - L[i,:i]@xs[:i])/L[i,i]
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
Ap=[[2.,1.,1.], [2.,1.,-4.],[1.,2.,1.]]
bs=[8.,-2.,2.]
A = np.matrix(Ap)
print(A)
print(bs)
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
testsolve(gauelim,A,bs)

[[ 2.  1.  1.]
 [ 2.  1. -4.]
 [ 1.  2.  1.]]
[8.0, -2.0, 2.0]
[nan nan nan]
[ 4. -2.  2.]


<ipython-input-3-40b4fdcefc11>:8: RuntimeWarning: divide by zero encountered in scalar divide
  coeff = A[i,j]/A[j,j]
<ipython-input-3-40b4fdcefc11>:9: RuntimeWarning: invalid value encountered in multiply
  A[i,j:] -= coeff*A[j,j:]
<ipython-input-3-40b4fdcefc11>:24: RuntimeWarning: invalid value encountered in scalar divide
  xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]


aussian elimnation doesn't work: \\
Example 3:
$(A|b)= \begin{bmatrix}  
  10^{-20} & -1 &   | 1 \\
  1 & 1 &   | 2 \end{bmatrix}$

In [4]:
import numpy as np
def gauelim(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
Ap=[[10.**(-20),-1.], [1.,1.]]
bs=[1.,2.]
A = np.matrix(Ap)
print(A)
print(bs)
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
testsolve(gauelim,A,bs)

[[ 1.e-20 -1.e+00]
 [ 1.e+00  1.e+00]]
[1.0, 2.0]
[ 0. -1.]
[ 3. -1.]


PARTIAL PIVOTING

Example 1:
$(A|b)= \begin{bmatrix}  
  0 & -1 &| 1 \\
  1 & 1 &| 2 \end{bmatrix}$

In [5]:
import numpy as np
def gauelim_pivot(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    k = np.argmax(np.abs(A[j:,j])) + j
#fIND INDEX OF MAXIMUM ENTRY IN COLUMN j
    if k != j:
      A[j,:], A[k,:] = A[k,:], A[j,:].copy()
#INTERCHANGE ROWS j and k
      bs[j], bs[k] = bs[k], bs[j]
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
Ap=[[0.,-1.], [1.,1.]]
bs=[1.,2.]
A = np.matrix(Ap)
print(A)
print(bs)
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
testsolve(gauelim_pivot,A,bs)

[[ 0. -1.]
 [ 1.  1.]]
[1.0, 2.0]
[ 3. -1.]
[ 3. -1.]


Partial Pivot
Example 2:
$(A|b)= \begin{bmatrix}  
  2 & 1 & 1 &| 8 \\
  2 & 1 & -4&|  -2 \\
  1 & 2 & 1 &| 2 \end{bmatrix}$

In [6]:
import numpy as np
def gauelim_pivot(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    k = np.argmax(np.abs(A[j:,j])) + j
    if k != j:
      A[j,:], A[k,:] = A[k,:], A[j,:].copy()
      bs[j], bs[k] = bs[k], bs[j]
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
Ap=[[2.,1.,1.], [2.,1.,-4.],[1.,2.,1.]]
bs=[8.,-2.,2]
A = np.array(Ap)
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
testsolve(gauelim_pivot,A,bs)

[ 4. -2.  2.]
[ 4. -2.  2.]


Partial Pivot
Example 3:
$(A|b)= \begin{bmatrix}  
  10^{-20} & -1 &| 1 \\
  1 & 1 &| 2 \end{bmatrix}$

In [7]:
import numpy as np
def gauelim_pivot(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    k = np.argmax(np.abs(A[j:,j])) + j
    if k != j:
      A[j,:], A[k,:] = A[k,:], A[j,:].copy()
      bs[j], bs[k] = bs[k], bs[j]
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
Ap=[[10**(-20),-1.], [1.,1.]]
bs=[1.,2]
A = np.matrix(Ap)
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
testsolve(gauelim_pivot,A,bs)

[ 3. -1.]
[ 3. -1.]


SCALED PARTIAL




Define for each row: a scale factor $s_{i}= max_{0\le j \le n-1}  |A_{ij}|$.


$s_i$ is the largest element in row $i$.


Instead of determining $k$ as corresponding to largest matrix element in column $j$ (at or below $A_{jj}$), as done in Partial Pivot, we determine $k$ by finding matrix element with largest relative magnitude, i.e., the largest in comparison to other elements in its row.


Thus we search for smallest integer $k$ that satisfies:

$\frac{|A_{kj}|}{s_{k}} = \max_{j\le m\le n-1} \frac{|A_{mj}|}{s_{m}}  $.

Then we interchange rows $j$ and $k$.

In [8]:
#scaled partial pivot
import numpy as np
def gauelim_pivot_scale(inA,inbs):
    A = np.copy(inA)
    bs = np.copy(inbs)
    n = bs.size
    scales = np.max(np.abs(A),axis=1)
#In a 2-dimensional NumPy array, the axes are the directions along the rows and columns.
#AXIS 0 IS THE DIRECTION ALONG THE ROWS, AXIS 1 IS THE DIRECTION ALONG THE COLUMNS

    for j in range(n-1):
        k = np.argmax(np.abs(A[j:,j])/scales[j:]) + j
        scales[j], scales[k] = scales[k], scales[j]
        bs[j], bs[k] = bs[k], bs[j]
        A[j,:], A[k,:] = A[k,:], A[j,:].copy()

        for i in range(j+1,n):
            coeff = A[i,j]/A[j,j]
            A[i,j:] -= coeff*A[j,j:]
            bs[i] -= coeff*bs[j]

    xs = backsub(A,bs)
    return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
Ap=[[10**(-20),-1.], [10**(-20),10**(-20)]]
bs=[1,2.*10**(-20)]
A = np.matrix(Ap)
print(A)
print(bs)
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
testsolve(gauelim_pivot_scale,A,bs)

[[ 1.e-20 -1.e+00]
 [ 1.e-20  1.e-20]]
[1, 2e-20]
[ 3. -1.]
[ 0. -1.]


Jacobi Iterative Method


$x_i^{k}=(b_{i} - \sum_{j=0}^{i-1} A_{ij}x_{j}^{k-1}- \sum_{j=i+1}^{n-1} A_{ij}x_{j}^{k-1})\frac{1}{A_{ii}}, i=0, 1, ..n-1$


convergence criteria:

$\sum_{i=0}^{n-1} |\frac{x_{i}^{k}-x_{i}^{k-1}}{x_{i}^k}| \le \epsilon$

In [9]:
import numpy as np
def termcrit(xolds,xnews):
  errs = np.abs((xnews - xolds)/xnews)
  return np.sum(errs)
def jacobi(A,bs,kmax=50,tol=1.e-6):
  n = bs.size
  xnews = np.zeros(n)
  for k in range(1,kmax):
    xs = np.copy(xnews)
    for i in range(n):
      slt = A[i,:i]@xs[:i]
      sgt = A[i,i+1:]@xs[i+1:]
      xnews[i] = (bs[i] - slt - sgt)/A[i,i]
    err = termcrit(xs, xnews)
    print(k, xnews, err)
    if err < tol:
      break
  else:
    xnews = None
  return xnews
def testcreate(n,val):
  A = np.arange(val,val+n*n).reshape(n,n)
  A = np.sqrt(A)
  bs = (A[0,:])**2.1
  return A, bs
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
n = 4; val = 21;
A, bs = testcreate(n,val)
A += val*np.identity(n)
testsolve(jacobi,A,bs)

1 [0.95584174 0.98382901 1.01264965 1.04197678] 4.0
2 [0.38609117 0.38784058 0.39421864 0.40425572] 6.158643474272702
3 [0.73341768 0.74941422 0.76835846 0.78969405] 1.9310672038734116
4 [0.52317706 0.53023862 0.54134654 0.55573114] 1.6555533665830167
5 [0.65072149 0.6631481  0.67896251 0.6975372 ] 0.8024076458188099
6 [0.57339977 0.58256412 0.59551555 0.61154376] 0.5539167512173229
7 [0.6202852  0.63142596 0.64611142 0.66368227] 0.30983792417040845
8 [0.59185737 0.60179949 0.61543315 0.63206832] 0.19712628238915642
9 [0.60909428 0.61976313 0.63403445 0.65123688] 0.11605599760545227
10 [0.59864294 0.60887114 0.62275581 0.63961427] 0.07162932168524415
11 [0.60497996 0.61547534 0.62959445 0.64666147] 0.04296480237007709
12 [0.6011376  0.61147098 0.62544794 0.6423885 ] 0.026221914973545257
13 [0.60346736 0.61389897 0.62796212 0.64497935] 0.015836323357587702
14 [0.60205475 0.61242679 0.62643768 0.64340843] 0.009625240606544867
15 [0.60291127 0.61331942 0.627362   0.64436094] 0.00582762295