**6.**

(a) What does the following code do?

(b) Can you determine the output if $k=2$?

(c) What is the advantage/disadvantage of doing it this way rather than the usual way? (2 marks)


https://www.google.com/url?q=https%3A%2F%2Fmathsfromnothing.au%2Fmatrix-inverse%2F

https://www.google.com/url?q=https%3A%2F%2Fcalvinmccarter.wordpress.com%2F2021%2F11%2F18%2Fthe-newton-schulz-iteration-for-matrix-inversion%2F

https://www.google.com/url?q=https%3A%2F%2Faalexan3.math.ncsu.edu%2Farticles%2Fmat-inv-rep.pdf

In [ ]:
import numpy as np
def undefined(A,kmax=50,tol=1.e-6):
  n = A.shape[0]
  xnews = np.transpose(A)
  for k in range(1,kmax):
    xs = np.copy(xnews)
    xnews = 2*xs - xs@A@xs
    err = abs(np.linalg.norm(xnews)-np.linalg.norm(xs))
    print(k,xnews, err)
    if err < tol:
      break
  return xnews
A1 = (1/np.sqrt(2))*np.array([[1, 1], [1, -1]])
A=A1/(np.linalg.norm(A1,np.inf))
p = undefined(A); print((p/(np.linalg.norm(A1,np.inf)))@A1)

1 [[ 0.75  0.75]
 [ 0.75 -0.75]] 0.5
2 [[ 0.9375  0.9375]
 [ 0.9375 -0.9375]] 0.375
3 [[ 0.99609375  0.99609375]
 [ 0.99609375 -0.99609375]] 0.1171875
4 [[ 0.99998474  0.99998474]
 [ 0.99998474 -0.99998474]] 0.007781982421875
5 [[ 1.  1.]
 [ 1. -1.]] 3.0517112463712692e-05
6 [[ 1.  1.]
 [ 1. -1.]] 4.656612873077393e-10
[[1.00000000e+00 1.01465364e-17]
 [1.01465364e-17 1.00000000e+00]]


Applying Newton's method to find inverse of a matrix

In [ ]:
import numpy as np
def undefined(A,kmax=200,tol=1.e-9):
  n = A.shape[0]
  xnews = np.transpose(A)
  for k in range(1,kmax):
    xs = np.copy(xnews)
    xnews = 2*xs - xs@A@xs
    err = abs(np.linalg.norm(xnews)-np.linalg.norm(xs))
    print(k,xnews/(np.linalg.norm(A1,np.inf)), err)
    if err < tol:
      break
  return xnews
A1 = np.array([[-2, 1,0], [1, -2,1],[0,1,-2]])
A=A1/(np.linalg.norm(A1,np.inf))
p = undefined(A); print((p/np.linalg.norm(A1,np.inf))@A1)

1 [[-0.1953125  0.0703125  0.0234375]
 [ 0.0703125 -0.171875   0.0703125]
 [ 0.0234375  0.0703125 -0.1953125]] 0.42384821873681466
2 [[-0.2791748   0.05285645  0.06262207]
 [ 0.05285645 -0.21655273  0.05285645]
 [ 0.06262207  0.05285645 -0.2791748 ]] 0.45993729998717203
3 [[-0.3661494   0.00744537  0.08379415]
 [ 0.00744537 -0.28235525  0.00744537]
 [ 0.08379415  0.00744537 -0.3661494 ]] 0.5232704373040178
4 [[-0.44580977 -0.07335357  0.04917893]
 [-0.07335357 -0.39663084 -0.07335357]
 [ 0.04917893 -0.07335357 -0.44580977]] 0.6423212866125785
5 [[-0.53671679 -0.19840751 -0.03676702]
 [-0.19840751 -0.57348381 -0.19840751]
 [-0.03676702 -0.19840751 -0.53671679]] 1.0789236770100423
6 [[-0.64343603 -0.3492958  -0.14343604]
 [-0.3492958  -0.78687207 -0.3492958 ]
 [-0.14343604 -0.3492958  -0.64343603]] 1.495029811324713
7 [[-0.72339152 -0.46236993 -0.22339152]
 [-0.46236993 -0.94678304 -0.46236993]
 [-0.22339152 -0.46236993 -0.72339152]] 1.1860041234854126
8 [[-0.74834103 -0.49765386 -0.2483

Trapeziodal Gezerlis

In [1]:
import numpy as np


def f(x): return np.sqrt(x)*np.cos(x)

def trapezoid(f,a,b,n):
  h = (b-a)/(n-1)
  xs = a + np.arange(n)*h
  cs = np.ones(n); cs[0] = 0.5; cs[-1] = 0.5
  contribs = cs*f(xs)
  return h*np.sum(contribs)
print(trapezoid(f, 0., np.pi, 5100), end=" ")

-0.894834657645572 

In [2]:
import numpy as np
def f(x):
  return np.sqrt(x)*np.cos(x)

def trapeze(f,a,b,n):
  h = (b-a)/(n-1)
  xs = a + np.arange(n)*h
  cs = np.ones(n); cs[0] = 0.5; cs[-1] = 0.5
  contribs = cs*f(xs)
  return h*np.sum(contribs)

def adaptive(f,a,b,simpson,kmax = 20,tol = 1.e-6):
  denom = 3
  n = 2
  val = trapeze(f,a,b,n)
  for k in range(kmax):
    nprime = 2*n-1
    valprime = trapeze(f,a,b,nprime)
    err = abs(valprime-val)/denom
    err /= abs(valprime)
    print(nprime, valprime, err)
    if err<tol:
      break
    n, val = nprime, valprime
  else:
    valprime = None
  return valprime
print(adaptive(f, 0., np.pi, trapeze)); print("")

3 -1.3920819992079265 0.3333333333333334
5 -1.056338333343367 0.10594574839859407
9 -0.9498046747146611 0.037387918261794356
17 -0.9138409458774788 0.013118157668983865
33 -0.9014541939325874 0.004580285213330047
65 -0.8971491275741257 0.0015995357687829622
129 -0.8956449881556915 0.0005597974786607915
257 -0.8951176226136272 0.00019638593809399814
513 -0.8949322730499143 6.903671905107309e-05
1025 -0.8948670172545393 2.4307446103436986e-05
2049 -0.8948440146042699 8.568588451927434e-06
4097 -0.8948358991255416 3.0230789564079614e-06
8193 -0.894833034166816 1.0672228286169633e-06
16385 -0.8948320223249948 3.769205824761148e-07
-0.8948320223249948



Simpson Composite


In [3]:
import numpy as np
def f(x):
  return np.sqrt(x)*np.cos(x)

def simpson(f,a,b,n):
  h = (b-a)/(n-1)
  xs = a + np.arange(n)*h
  cs = 2*np.ones(n)
  cs[1::2] = 4; cs[0] = 1; cs[-1] = 1
  contribs = cs*f(xs)
  return (h/3)*np.sum(contribs)
print(simpson(f, 0., np.pi, 501), end=" ")


-0.8948719029807339 

Adaptive Simpson

In [4]:
import numpy as np
def f(x):
  return np.sqrt(x)*np.cos(x)

def simpson(f,a,b,n):
  h = (b-a)/(n-1)
  xs = a + np.arange(n)*h
  cs = 2*np.ones(n)
  cs[1::2] = 4; cs[0] = 1; cs[-1] = 1
  contribs = cs*f(xs)
  return (h/3)*np.sum(contribs)

def adaptive(f,a,b,simpson,kmax = 20,tol = 1.e-6):
  denom = 15
  n = 2
  val = simpson(f,a,b,n)
  for k in range(kmax):
    nprime = 2*n-1
    valprime = simpson(f,a,b,nprime)
    err = abs(valprime-val)/denom
    err /= abs(valprime)
    print(nprime, valprime, err)
    if err<tol:
      break
    n, val = nprime, valprime
  else:
    valprime = None
  return valprime
print(adaptive(f, 0., np.pi, simpson)); print("")


3 -0.9280546661386176 0.06666666666666668
5 -0.9444237780551803 0.0011554920080666191
9 -0.914293455171759 0.002196984109276749
17 -0.9018530362650847 0.0009196190810419056
33 -0.8973252766176234 0.0003363893239493752
65 -0.8957141054546385 0.00011991706975647414
129 -0.8951436083495465 4.248831135552376e-05
257 -0.8949418340996058 1.503071613167845e-05
513 -0.89487048986201 5.315051239560298e-06
1025 -0.8948452653227479 1.8792477492763297e-06
2049 -0.8948363470541802 6.644245507010768e-07
-0.8948363470541802

