Solving $Ax=b$ for lower and upper triangular matrices

In [1]:
import numpy as np
def forsub(L,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in range(n):
    xs[i] = (bs[i] - L[i,:i]@xs[:i])/L[i,i]
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
def testcreate(n,val):
  A = np.arange(val,val+n*n).reshape(n,n)
  A = np.sqrt(A)
  bs = (A[0,:])**2.1
  return A, bs
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)

A, bs = testcreate(4,21)
print(A)
print(bs)
L = np.tril(A)
print(L)
testsolve(forsub,L,bs)
print(" ")
U = np.triu(A)
print(U)
testsolve(backsub,U,bs)

[[4.58257569 4.69041576 4.79583152 4.89897949]
 [5.         5.09901951 5.19615242 5.29150262]
 [5.38516481 5.47722558 5.56776436 5.65685425]
 [5.74456265 5.83095189 5.91607978 6.        ]]
[24.45289367 25.67697243 26.90383729 28.13337297]
[[4.58257569 0.         0.         0.        ]
 [5.         5.09901951 0.         0.        ]
 [5.38516481 5.47722558 5.56776436 0.        ]
 [5.74456265 5.83095189 5.91607978 6.        ]]
[ 5.33605887 -0.19676761 -0.13541854 -0.09524368]
[ 5.33605887 -0.19676761 -0.13541854 -0.09524368]
 
[[4.58257569 4.69041576 4.79583152 4.89897949]
 [0.         5.09901951 5.19615242 5.29150262]
 [0.         0.         5.56776436 5.65685425]
 [0.         0.         0.         6.        ]]
[0.14941285 0.10032435 0.06814924 4.6888955 ]
[0.14941285 0.10032435 0.06814924 4.6888955 ]


Gaussian elimination


In [2]:
import numpy as np
def gauelim(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs

def forsub(L,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in range(n):
    xs[i] = (bs[i] - L[i,:i]@xs[:i])/L[i,i]
  return xs
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs
def testcreate(n,val):
  A = np.arange(val,val+n*n).reshape(n,n)
  A = np.sqrt(A)
  bs = (A[0,:])**2.1
  return A, bs
def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)
  xs = np.linalg.solve(A,bs); print(xs)
#if _name == '_main_':
A, bs = testcreate(4,21)
print(A)
print(bs)
testsolve(gauelim,A,bs)

[[4.58257569 4.69041576 4.79583152 4.89897949]
 [5.         5.09901951 5.19615242 5.29150262]
 [5.38516481 5.47722558 5.56776436 5.65685425]
 [5.74456265 5.83095189 5.91607978 6.        ]]
[24.45289367 25.67697243 26.90383729 28.13337297]
[ 17118.9554009  -55069.99934969  58822.07580723 -20866.39246612]
[ 17118.95550576 -55069.99968225  58822.07615809 -20866.39258928]
