# Assignment 5

## Problem 4.9
In this problem we will evaluate the sum $\sum_{k=0}^{n-1}k^2$ needed for Eqn 4.82. The trick we'll use is to start from the following sum

$$
\sum_{k=0}^{N}\left[(k+1)^3-k^3\right]
$$

First evaluate this sum without expanding the parentheses: you will notice that it involves a telescoping series and is therefore straightforward. Now that you know what this sum is equal to, expand the parentheses and solve for the sum we started with. Finally, it should be trivial to re-express the final result for the case $N = n - 1$.

**Solution:** Evaluating the sum without expanding the parentheses,

$$
\sum_{k=0}^{N}\left[(k+1)^3-k^3\right] = (1^3-0^3)+(2^3-1^3)+(3^3-2^3)+...+[N^3-(N-1)^3]+[(N+1)^3-N^3]
$$

Since this is a telescopic series all terms will cancel out except the first and last terms,

$$
\sum_{k=0}^{N}\left[(k+1)^3-k^3\right] = (N+1)^3-0^3 = (N+1)^3
$$

Now, expanding the parenthesis,

$$
\sum_{k=0}^{N}\left[(k+1)^3-k^3\right] = \sum_{k=0}^{N}\left[k^3+1^3+3k^2+3k-k^3\right]\\
\implies (N+1)^3=3\sum_{k=0}^{N}k^2+3\sum_{k=0}^{N}k+\sum_{k=0}^{N}1\\
\implies 3\sum_{k=0}^{N}k^2 = (N+1)^3 - 3\left(\frac{N(N+1)}{2}\right) - (N+1)\\
=\frac{(2N^3+2+6N^2+6N)-3N^2-3N-2N-2}{2}\\
=\frac{2N^3+3N^2+N}{2}\\
=\frac{N(2N^2+3N+1)}{2}\\
=\frac{N(N+1)(2N+1)}{2}\\
$$

Hence the summation equates to,

$$
\sum_{k=0}^{N}k^2 = \frac{N(N+1)(2N+1)}{6}
$$

on changing the $N=n-1$,
\begin{align*}
  \boxed{\sum_{k=0}^{n-1}k^2 = \frac{n(n-1)(2n-1)}{6}}
\end{align*}

## Problem 4.10

Update `gauelim.py` such that it can handle multiple constant vectors. In other words, generalize `gauelim()` such that it takes in an $n × n$ matrix $A$ and an $n × m$ matrix $B$, where $m$ is the number of distinct constant vectors you will be handling. The output
should be an $n × m$ matrix $X$, collecting all the solution vectors:

$$
\vec{X}=(\vec{x_0}\,\,\,\,\vec{x_1}\dots\,\,\vec{x_{m-1}})\\
\vec{B}=(\vec{b_0}\,\,\,\,\vec{b_1}\dots\,\,\vec{b_{m-1}})
$$

Test out the case where $A$ is a $4 × 4$ matrix and $B$ is $4 × 3$.

In [ ]:
import numpy as np

def backsub(U,bs):
  ''' Back subtitution algorithm for an upper triangular matrix'''
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs

def testcreate(n,m,val):
  '''Test function to create a n x n and an n x m matrix'''
  A = np.arange(val,val+n*n).reshape(n,n)
  A = np.sqrt(A)
  bs = (A[:m,:])**2.1
  if m > n:
    for i in range(0, m-n):
      bs = np.append(bs, [bs[0]**(i/2+0.2)], axis=0)
  return A, bs

def testsolve(f,A,B):
  '''Test function to generate a solution matrix using custom code and library code for comparison'''
  X = f(A, B)
  Xlib = []
  for i in range(len(B)):
    xs = np.linalg.solve(A,B[i])
    Xlib.append(xs)
  return X, np.array(Xlib)

In [ ]:
def gauelim(inA, inB):
  X = [] # solution vectors are stored here
  n = inB[0].size

  # create a lower triangular matrix from A by performing gausian elimination
  # and store the require coefficients in another matrix
  coeffs = np.zeros(np.shape(inA))
  A = np.copy(inA)
  for j in range(n-1):
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      coeffs[i][j] = coeff

  # iterate each item of bi and perfrom operations as per the
  # previously created coefficient matrix
  for inbs in inB:
    bs = np.copy(inbs)
    for j in range(n-1):
      for i in range(j+1,n):
        bs[i] -= coeffs[i][j]*bs[j]

    # finally perform back substitution using the
    # previously calculated lower triangular matrix
    xs = backsub(A,bs)
    X.append(xs)

  return np.array(X)

In [ ]:
# testing
A, B = testcreate(n=4, m=3, val=21)
print('Matrix A')
print(A)
print('\nMatrix B (Constant Vectors)')
print(np.transpose(B))
X, Xlib = testsolve(gauelim, A, B)
print('\nSolution Vectors')
print(np.transpose(X))
print('\nSolution Vectors generated using numpy.linalg.solve()')
print(np.transpose(Xlib))

Matrix A
[[4.58257569 4.69041576 4.79583152 4.89897949]
 [5.         5.09901951 5.19615242 5.29150262]
 [5.38516481 5.47722558 5.56776436 5.65685425]
 [5.74456265 5.83095189 5.91607978 6.        ]]

Matrix B (Constant Vectors)
[[24.45289367 29.36547358 34.31767822]
 [25.67697243 30.60004149 35.5612745 ]
 [26.90383729 31.83698643 36.80694553]
 [28.13337297 33.07622465 38.05462768]]

Solution Vectors
[[ 17118.9554009   14276.82461745  11407.7199386 ]
 [-55069.99934969 -45710.45691492 -36261.30692494]
 [ 58822.07580723  48582.47137498  38244.03373634]
 [-20866.39246612 -17143.88975603 -13385.187617  ]]

Solution Vectors generated using numpy.linalg.solve()
[[ 17118.95550576  14276.82470448  11407.72000762]
 [-55069.99968225 -45710.45719093 -36261.30714383]
 [ 58822.07615809  48582.47166618  38244.03396728]
 [-20866.39258928 -17143.88985825 -13385.18769806]]
