# Assignment 6

In [ ]:
import numpy as np

## Problem 4.14

Prove (by contradiction) that Doolittle’s LU decomposition is unique.

**Proof:** Let matrix $A=LU$, by the means of Doolittle’s LU decomposition.

Assume that $L$ and $U$ are not unique. Hence there exists some $L'$ and $U'$ s.t. $A=L'U'$, $L'\ne L$ and $U'\ne U$.

Hence,
$$
L = \begin{pmatrix}
1 & 0 & 0\\
L_{10} & 1 & 0\\
L_{20} & L_{21} & 1
\end{pmatrix},\,\,\,U = \begin{pmatrix}
U_{00} & U_{01} & U_{02}\\
0 & U_{11} & U_{12}\\
0 & 0 & U_{22}
\end{pmatrix}
$$

$$
L' = \begin{pmatrix}
1 & 0 & 0\\
L'_{10} & 1 & 0\\
L'_{20} & L'_{21} & 1
\end{pmatrix},\,\,\,U = \begin{pmatrix}
U'_{00} & U'_{01} & U'_{02}\\
0 & U'_{11} & U'_{12}\\
0 & 0 & U'_{22}
\end{pmatrix}
$$

Now, multiplying to get $A=LU=L'U'$,

$$
A = \begin{pmatrix}
U_{00} & U_{01} & U_{02}\\
U_{00}L_{10} & U_{01}L_{10}+U_{11} & U_{02}L_{10}+U_{12}\\
U_{00}L_{20} & U_{01}L_{20}+U_{11}L_{21} &U_{02}L_{20}+U_{12}L_{21}+U_{22}
\end{pmatrix}\\
=\begin{pmatrix}
U'_{00} & U'_{01} & U'_{02}\\
U'_{00}L'_{10} & U'_{01}L'_{10}+U'_{11} & U'_{02}L'_{10}+U'_{12}\\
U'_{00}L'_{20} & U'_{01}L'_{20}+U'_{11}L'_{21} &U'_{02}L'_{20}+U'_{12}L'_{21}+U'_{22}
\end{pmatrix}
$$

Comparing the terms on the first row, we get

$$
U_{00}=U'_{00},\,\,\,U_{01}=U'_{01}\,\,\,U_{02}=U'_{02}
$$

Substituting them in the second and third rows, we get,
$$
L_{10}=L'_{10},\,\,\,U_{11}=U'_{11}\,\,\,U_{12}=U'_{12}\\
L_{20}=L'_{20},\,\,\,L_{11}=L'_{21}\,\,\,U_{22}=U'_{22}\\
\therefore L'=L \text{  and  } U'=U
$$

Hence our assumption is proven wrong. Thus, Doolittle’s LU decomposition is unique for every matrix.

## Problem 4.17

Use Gaussian elimination or LU decomposition (without and with pivoting) for:

``` python
A = np.array([4., 4, 8, 4, 4, 5, 3, 7, 8,3, 9, 9, 4, 7, 9, 5]).reshape(4,4)
bs = np.array([1., 2, 3, 4])

```
Does pivoting help in any way? What are your conclusions about this matrix? You
sometimes hear the advice that, since the problem arises from one of the $U_{ii}$'s being
zero, you should replace it with a small number, say $10^{−20}$. Does this work?

In [ ]:
A = np.array([4., 4, 8, 4, 4, 5, 3, 7, 8, 3, 9, 9, 4, 7, 9, 5]).reshape(4,4)
bs = np.array([1., 2, 3, 4])

def gauelim(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs

def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs

def gauelim_pivot(inA,inbs):
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size
  for j in range(n-1):
    k = np.argmax(np.abs(A[j:,j])) + j
    if k != j:
      A[j,:], A[k,:] = A[k,:], A[j,:].copy()
      bs[j], bs[k] = bs[k], bs[j]
    for i in range(j+1,n):
      coeff = A[i,j]/A[j,j]
      A[i,j:] -= coeff*A[j,j:]
      bs[i] -= coeff*bs[j]
  xs = backsub(A,bs)
  return xs

def gauelim_pivot_scale(inA,inbs):
    A = np.copy(inA)
    bs = np.copy(inbs)
    n = bs.size
    scales = np.max(np.abs(A),axis=1)

    for j in range(n-1):
        k = np.argmax(np.abs(A[j:,j])/scales[j:]) + j
        scales[j], scales[k] = scales[k], scales[j]
        bs[j], bs[k] = bs[k], bs[j]
        A[j,:], A[k,:] = A[k,:], A[j,:].copy()

        for i in range(j+1,n):
            coeff = A[i,j]/A[j,j]
            A[i,j:] -= coeff*A[j,j:]
            bs[i] -= coeff*bs[j]

    xs = backsub(A,bs)
    return xs

def testsolve(f,A,bs):
  xs = f(A,bs); print(xs)

**Solution:** In the following three cell blocks, we have attempted to solve perform gaussian elimination without pivoting, with pivoting and with scaled pivoting. But none of the methods seem to work in this case.

In [ ]:
testsolve(gauelim,A,bs)

[nan nan inf inf]


<ipython-input-10-be3ea33d55d9>:20: RuntimeWarning: divide by zero encountered in scalar divide
  xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
<ipython-input-10-be3ea33d55d9>:20: RuntimeWarning: invalid value encountered in matmul
  xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]


In [ ]:
testsolve(gauelim_pivot,A,bs)

[ nan  inf -inf -inf]


<ipython-input-10-be3ea33d55d9>:20: RuntimeWarning: divide by zero encountered in scalar divide
  xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
<ipython-input-10-be3ea33d55d9>:20: RuntimeWarning: invalid value encountered in matmul
  xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]


In [ ]:
testsolve(gauelim_pivot_scale,A,bs)

[ nan  inf -inf -inf]


<ipython-input-10-be3ea33d55d9>:20: RuntimeWarning: divide by zero encountered in scalar divide
  xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
<ipython-input-10-be3ea33d55d9>:20: RuntimeWarning: invalid value encountered in matmul
  xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]


Now, because these errors seem to arise froom $U_{ii}$ being zero and encountering zero division error, we have modified the back-substitution code to replace if $U_{ii}=0$ with $U_{ii}=10^{-20}$.

In [ ]:
def backsub(U,bs):
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    if U[i,i] == 0:
      U[i,i] = 1.e-20
    xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
  return xs

In [ ]:
testsolve(gauelim_pivot,A,bs)

[ 3.e+20  1.e+20 -1.e+20 -2.e+20]


This, however outputs very large numbers for our solution matrix (possibly due to the denominator $U_{ii}$ being very small). None of these methods actually work however because the matrix is singular, i.e. $\det(A)=0$, hence $A^{-1}$ does not exist. There is no possible solution for any version of `bs` in this case.

We can check this by using NumPy.

In [ ]:
print('Determinant of A = ', np.linalg.det(A))

Determinant of A =  0.0


Additionally, we can see that NumPy's built-in matrix solver code will throw up a `LinAlgError: Singular matrix` error as expected.

In [ ]:
np.linalg.solve(A, bs)

LinAlgError: Singular matrix

## Problem 4.18

We will now employ the Jacobi iterative method to solve a linear system of equations,
for the case where the coefficient matrix is sparse; we won’t need to explicitly store
$A$. Focus on the following cyclic tridiagonal matrix:

$$
\left(\hspace{-5pt}\begin{array}{ccccccccc|c}
  4 & -1 & 0 & 0 & ... & 0 & 0 & 0 & -1 & 1 \\
  -1 & 4 & -1 & 0 & ... & 0 & 0 & 0 & 0 & 1 \\
  \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
  0 & 0 & 0 & 0 & ... & 0 & -1 & 4 & -1 & 1 \\
  -1 & 0 & 0 & 0 & ... & 0 & 0 & -1 & 4 & 1
\end{array}\hspace{-5pt}\right)
$$

Something similar appears when you study differential equations with periodic boundary conditions, as we will see in section 8.4.2. (Note that A is “almost” a tridiagonal
matrix.) For this problem, the Jacobi iterative method of Eq. (4.121) turns into:

$$
x^{(k)}_0 = \left(1+x^{(k-1)}_1+x^{(k-1)}_{n-1}\right)\frac{1}{4}\\
x^{(k)}_i = \left(1+x^{(k-1)}_{i-1}+x^{(k-1)}_{i+1}\right)\frac{1}{4},\,\,\,i=1,2,3,...,n-2\\
x^{(k)}_{n-1} = \left(1+x^{(k-1)}_0+x^{(k-1)}_{n-2}\right)\frac{1}{4}\\
$$

Implement the Jacobi iterative method for this set of equations. Your input parameters should be only the total number of iterations, the tolerance, as well as $n$ (which
determines the size of the problem), i.e., there are no longer any $A$ and $b$ to be passed
in. Choose a tolerance of $10^{−5}$ and print out the solution vectors for $n = 10$ and for $n = 20$, each time also comparing with the output of `numpy.linalg.solve()`. (To
produce the latter, you will have to form A and b explicitly.)

In [ ]:
def termcrit(xolds,xnews):
  errs = np.abs((xnews - xolds)/xnews)
  return np.sum(errs)

def jacobi_cyclic(n,kmax=50,tol=1.e-5):
  xnews = np.zeros(n)

  for k in range(1,kmax):
    xs = np.copy(xnews)
    for i in range(n):
      # cylic iterative variables
      p = i-1 if i != 0 else n-1
      q = i+1 if i != n-1 else 0

      xnews[i] = (1 + xs[p] + xs[q])/4

    err = termcrit(xs, xnews)
    print(f'[{k}]: {err}')

    if err < tol:
      break
  else:
    xnews = None
  return xnews

def generate_cyclic_matrix(n):
  A = np.zeros((n, n))
  for i in range(n):
    A[i][i] = 4
    p = i-1 if i != 0 else n-1
    q = i+1 if i != n-1 else 0
    A[i][p] = -1
    A[i][q] = -1
  return A

def testsolve(f,n):
  # generate the matrix explicitly to pass to the NumPy solve function
  A = generate_cyclic_matrix(n)
  bs = np.ones(n)

  print('Matrix generated for n =', n)
  print(A)

  print('\nJacobi iterative solution relative error')
  print('[n]: Error')
  xs = f(n)

  print('\nFinal solution based on Jacobi iterative method:')
  xs1 = np.linalg.solve(A,bs)
  print(xs)
  print('\nSolution according to numpy.linalg.solve():')
  print(xs1)

In [ ]:
testsolve(jacobi_cyclic, n=10)

Matrix generated for n = 10
[[ 4. -1.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  4. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  4. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  4. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  4. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  4. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  4. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  4. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  4. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0. -1.  4.]]

Jacobi iterative solution relative error
[n]: Error
[1]: 10.0
[2]: 3.3333333333333335
[3]: 1.4285714285714284
[4]: 0.6666666666666666
[5]: 0.32258064516129026
[6]: 0.15873015873015872
[7]: 0.07874015748031496
[8]: 0.0392156862745098
[9]: 0.019569471624266144
[10]: 0.009775171065493644
[11]: 0.004885197850512946
[12]: 0.002442002442002442
[13]: 0.0012208521548040532
[14]: 0.0006103888176768602
[15]: 0.0003051850947599719
[16]: 0.00015259021896696422
[17]: 7.629452739355005e-05
[18]: 3.8147118175957395e-05
[19]: 1.907352270798246e-05
[2

In [ ]:
testsolve(jacobi_cyclic, n=20)

Matrix generated for n = 20
[[ 4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0. -1.]
 [-1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  4. -1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.

**Solution:** Hence, for both $n=10, 20$ our modified Jacobi algorithm produces a result really close the required value.