# Assignment 4

In [57]:
import numpy as np
import matplotlib.pyplot as plt

## Problem 3.14

In the main text we used Richardson extrapolation in order to rederive a second forward-difference formula for the first derivative, see Eq. (3.49). Do the same (i.e., don’t use Taylor series) for the third forward difference for the first derivative.

**Solution:** According to the Richardson extrapolation, exact answer of the calculation G is given by

$$
G = \frac{2^pg(h/2)-g(h)}{2^p-1}+O(h^{p+q})
$$

where $g(h)$ is the approximate answer and $p$ denotes the order of the leading error term and $q$ is the increment in the order for the error terms after that. The second forward-difference formula for the first derivative is,

$$
D_{fd}(h) = \frac{4f(x+\frac{h}{2})- f(x+h)-3f(x)}{h} + O(h^2)
$$

For the third forward difference for the first derivative, $p=2$ and $q=1$.

$$
R_{fd} = \frac{4D_{fd}(h/2)-D_{fd}(h)}{4-1} + O(h^3)\\
R_{fd}= \frac{1}{3}\left(\frac{4\left[4f(x+\frac{h}{4})-f(x+\frac{h}{2})-3f(x)\right]}{h/2} - \frac{4f(x+\frac{h}{2})-f(x+h)-3f(x)}{h}\right)+ O(h^3)\\
R_{fd}= \frac{32f(x+\frac{h}{4})-12f(x+\frac{h}{2})+f(x+h)-21f(x)}{3h}+ O(h^3)
$$

Hence, $R_{fd}$ is the third forward difference for the first derivative with the leading error term of the order $O(h^3)$.

## Problem 3.16

We will now discuss an application of Richardson extrapolation which does not involve finite differences. Inspired by Archimedes’ approach to approximating the value of $\pi$ (namely inscribing a regular polygon in a circle with unit diameter), we write down the perimeter of a polygon with $2^n$ angles $g_n = 2^n \sin(\pi/2^n)$.

(a) Set $h = 2^{−n}$ and then Taylor/Maclaurin expand the sine so as to produce a systematic theory for the dependence of $g$ on $h$, i.e., $g(h)$.

**Solution:** We know that,

$$
\sin(x) = x - \frac{x^3}{3!} + \frac{x^5}{5!} - \frac{x^7}{7!} + \frac{x^9}{9!} + ...\\
\implies 2^n \sin(\pi/ 2^n) = \pi - \frac{\pi^3}{3!  (2^n)^2} + \frac{\pi^5}{5!  (2^n)^4} - \frac{\pi^7}{7!  (2^n)^6} + ...
$$

putting $h=2^{-n}$,

$$
    g(h) = \pi  - \frac{\pi^3 h^2}{3!} + \frac{\pi^5 h^4}{5!} - \frac{\pi^7 h^6}{7!} + O(h^8)\\
    \implies g(h) = \pi + \sum_{n=1}^\infty \frac{(-1)^n \pi^{2n+1} h^{2n}}{(2n+1)!}
$$

(b) In the previous part you should have found that, to begin with, in the language
of Eq. (3.47) you have:

$$
G=\frac{4g(h/2)-g(h)}{3} + O(h^4)
$$

Take $n = 2, . . ., 10$ and apply $g_n = 2^n \sin(\pi/2^n)$. Then, use those values as input to Eq. (3.91) to produce extrapolated estimates.

**Solution:** For $O(h^4)$ error, where $p=2$ and $q=2$
$$
    g(h) = \pi  - \frac{\pi^3 h^2}{3!} + O(h^4)\\
$$


In [148]:
ns = [i for i in range(2,11)]
ps = [2**n * np.sin(np.pi/2**n) for n in ns]
qs = [(4*ps[i+1] - ps[i])/3 for i in range(8)]
rs = [(16*qs[i+1] - qs[i])/15 for i in range(7)]
print(ps)
print(qs)
print(rs)

n = 2; Approximation of pi: 3.0772888734507617; Error bar: 0.06430378013903137
n = 3; Approximation of pi: 3.1174064272510473; Error bar: 0.024186226338745787
n = 4; Approximation of pi: 3.1350345214949917; Error bar: 0.006558132094801383
n = 5; Approximation of pi: 3.1399211225212427; Error bar: 0.001671531068550447
n = 6; Approximation of pi: 3.141172770750749; Error bar: 0.000419882839044039
n = 7; Approximation of pi: 3.1414875578732473; Error bar: 0.00010509571654582217
n = 8; Approximation of pi: 3.1415663718477; Error bar: 2.6281742093292593e-05
n = 9; Approximation of pi: 3.1415860826659596; Error bar: 6.570923833493225e-06
n = 10; Approximation of pi: 3.1415910108283147; Error bar: 1.6427614784042532e-06


Here, we can see that the error bar has is of the order of $10^{-6}$ for $n=10$. We can observe that as $n$ increases, the value of $\pi$ gets closer and closer to the real value.

(c) You should now see a pattern following from the above Taylor expansion. In
the previous part you cancelled the error $O(h^2)$, so you were left with a theory
having $p = 4$ and $q = 2$. Apply Eq. (3.47) to the results you produced in the
previous part to carry out a further round of Richardson extrapolation. (This is
quite similar to what we will encounter in Eq. (7.87).)

**Solution:** For a further round of Richardson extrapolation, we cancel out the $O(h^4)$ error. Here, $p=4$ and $q=2$.
$$
    g(h) = \pi  - \frac{\pi^3 h^2}{3!} + \frac{\pi^5 h^4}{5!}+ O(h^6)\\
$$


In [146]:
p = 4
for n in range(2, 11):
    # Here n is the number of iterations
    pi_approx = richardson(n, p)
    print(f"n = {n}; Approximation of pi: {pi_approx}; Error bar: {abs(np.pi-pi_approx)}")

n = 2; Approximation of pi: 3.1424471995626337; Error bar: 0.0008545459728406257
n = 3; Approximation of pi: 3.14145815663389; Error bar: 0.0001344969559031739
n = 4; Approximation of pi: 3.1415362019553057; Error bar: 5.6451634487419966e-05
n = 5; Approximation of pi: 3.1415771097327108; Error bar: 1.5543857082356283e-05
n = 6; Approximation of pi: 3.141588678173762; Error bar: 3.975416031032353e-06
n = 7; Approximation of pi: 3.1415916541449675; Error bar: 9.994448255667976e-07
n = 8; Approximation of pi: 3.1415924033791596; Error bar: 2.502106335455778e-07
n = 9; Approximation of pi: 3.141592591015296; Error bar: 6.257449713942265e-08
n = 10; Approximation of pi: 3.141592637944804; Error bar: 1.5644989304064438e-08


Here, we can see that the error bar has further decreased down to the order of $10^{-8}$ for $n=10$, which is two orders less that the previous part (b), as predicted by Richardson extrapolation.

## Problem 4.5

For a matrix A, implement: (a) finding the lower and upper triangular part, (b) the
Frobenius norm, and (c) the infinity norm. You can use NumPy but, obviously, you
shouldn’t use the functions that have been designed to give the corresponding answer
each time.

### Upper and Lower triangular part

In [108]:
def upper_triangular(M):
    rows, cols = len(M), len(M[0])
    N = [[] for _ in range(rows)]
    for i in range(rows):
        for j in range(cols):
            if i > j:
                N[i].append(0)
            else:
                N[i].append(M[i][j])
    return N

def lower_triangular(M):
    rows, cols = len(M), len(M[0])
    N = [[] for _ in range(rows)]
    for i in range(rows):
        for j in range(cols):
            if i < j:
                N[i].append(0)
            else:
                N[i].append(M[i][j])
    return N

In [109]:
M = [[1,2,3],[4,5,6],[7,8,9],[9,5,1]]
print('Upper triangular matrix of M calculated:')
for row in upper_triangular(M):
    print(row)
print('Upper triangular matrix of M using NumPy:')
for row in np.triu(M):
    print(row)

Upper triangular matrix of M calculated:
[1, 2, 3]
[0, 5, 6]
[0, 0, 9]
[0, 0, 0]
Upper triangular matrix of M using NumPy:
[1 2 3]
[0 5 6]
[0 0 9]
[0 0 0]


In [110]:
M = [[1,2,3],[4,5,6],[7,8,9],[9,5,1]]
print('Lower triangular matrix of M calculated:')
for row in lower_triangular(M):
    print(row)
print('Lower triangular matrix of M using NumPy:')
for row in np.tril(M):
    print(row)

Lower triangular matrix of M calculated:
[1, 0, 0]
[4, 5, 0]
[7, 8, 9]
[9, 5, 1]
Lower triangular matrix of M using NumPy:
[1 0 0]
[4 5 0]
[7 8 9]
[9 5 1]


### Frobenius norm

In [111]:
def frobenius_norm(M):
    norm = 0
    rows, cols = len(M), len(M[0])
    for i in range(rows):
        for j in range(cols):
            norm += M[i][j]**2

    return norm**0.5

print('Frobenius norm of M calculated : ', frobenius_norm(M))
print('Frobenius norm of M using NumPy: ', np.linalg.norm(M))

Frobenius norm of M calculated :  19.79898987322333
Frobenius norm of M using NumPy:  19.79898987322333


### Infinity norm

In [112]:
def infinity_norm(M):
    # if M is not a column vector, we convert in into one
    N = [sum(row) for row in M] 
    xi = [abs(row) for row in N] 
    return max(xi)

print('Infinity norm of M calculated : ', infinity_norm(M))
print('Infinity norm of M using NumPy: ', np.linalg.norm(M, ord=np.inf))

Infinity norm of M calculated :  24
Infinity norm of M using NumPy:  24.0


## Problem 4.8

Evaluate the norm and condition number $\kappa (A)$ for the $4 × 4$, $10 × 10$, and $20 × 20$
matrices you get from `triang.testcreate()`; feel free to use NumPy functionality.

**Solution:** Using the formula $\kappa(M) = ||M||\times||M^{-1}||$

In [113]:
def testcreate(n,val):
    A = np.arange(val,val+n*n).reshape(n,n)
    A = np.sqrt(A)
    bs = (A[0,:])**2.1
    return A, bs

def kappa(M):
    Minv = np.linalg.inv(M)
    return np.linalg.norm(M)*np.linalg.norm(Minv)

def norm(M):
    norm = 0
    rows, cols = len(M), len(M[0])
    for i in range(rows):
        for j in range(cols):
            norm += M[i][j]**2

    return norm**0.5

In [97]:
fourM, _ = testcreate(4, 21)
tenM, _ = testcreate(10, 21)
twentyM, _ = testcreate(20, 21)

In [117]:
print('Norms')
print('Matrix       | Calculated norm    | Using linalg.norm()')
print('-'*54)
print('4x4 matrix   |', norm(fourM), '|', np.linalg.norm(fourM))
print('10x10 matrix |', norm(tenM), ' |', np.linalg.norm(tenM))
print('20x20 matrix |', norm(twentyM), '|', np.linalg.norm(twentyM))

Norms
Matrix       | Calculated norm    | Using linalg.norm()
------------------------------------------------------
4x4 matrix   | 21.354156504062622 | 21.354156504062622
10x10 matrix | 83.96427811873333  | 83.96427811873333
20x20 matrix | 296.98484809834997 | 296.98484809834997


In [122]:
print('Condition numbers')
print('Matrix       | Calculated kappa       | Using linalg.cond()')
print('-'*70)
print('4x4 matrix   |', kappa(fourM), '     |', np.linalg.cond(fourM))
print('10x10 matrix |', kappa(tenM), '|', np.linalg.cond(tenM))
print('20x20 matrix |', kappa(twentyM), '|', np.linalg.cond(twentyM))

Condition numbers
Matrix       | Calculated kappa       | Using linalg.cond()
----------------------------------------------------------------------
4x4 matrix   | 286206168.8401083      | 286204585.7850762
10x10 matrix | 4.8405393063922456e+16 | 4.4203343826650816e+17
20x20 matrix | 1.3100221871120957e+18 | 2.2754580965939308e+18


Here, we can see that while the norm is calculated accurately, the condition numbers are not that accurate, although their order is roughly the same. These matrices have high values of $\kappa$, which means that a small perturbation can lead to a large amplifications while performing operations with these matrices.